name: Frontend CI

on:
  push:
    branches: [develop, master]
    paths:
      - 'client/**'
  pull_request:
    branches:
      - [develop, master]
    paths:
      - 'client/**'
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2022, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code to runner
        uses: actions/checkout@v3

      - name: Set up JS environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Run tests
        working-directory: client
        run: npm test
